name: wearcodes
description: "Store and view your QR/barcode codes easily on your smartwatch."
publish_to: "none"
version: 1.0.2+43
environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  wear_plus: ^1.2.3
  wearable_rotary: ^2.0.2
  barcode_widget: ^2.0.4
  shared_preferences: ^2.5.3
  wearthat: ^0.0.1

dev_dependencies:
  rename_app: ^1.6.5
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  image_path: "assets/icon.png"
