name: Build and Release APK

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build release APK
        run: flutter build apk --release

      - name: Rename APK
        run: mv build/app/outputs/flutter-apk/app-release.apk wearcodes-release-${{ github.ref_name }}.apk
        run: mv build/app/outputs/flutter-apk/app-release.apk.sha1 wearcodes-release-${{ github.ref_name }}.apk.sha1
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: wearcodes-release-${{ github.ref_name }}.*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
