name: Build and Release APK

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Cache Gradle
        uses: actions/Cache
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Cache pub
        uses: actions/Cache
        with:
          path: |
            ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Install dependencies
        run: flutter pub get

      - name: Update pubspec version
        run: |
          VERSION=${GITHUB_REF_NAME#v} # strips leading 'v'
          BUILD_NUMBER=${GITHUB_RUN_NUMBER}
          sed -i "s/^version: .*/version: ${VERSION}+${BUILD_NUMBER}/" pubspec.yaml

      - name: Setup keystore
        run: |
          echo "$KEYSTORE_BASE64" | base64 --decode > ./android/release-key.jks
        env:
          KEYSTORE_BASE64: ${{secrets.KEYSTORE_BASE64}}

      - name: Create key.properties
        run: |
          echo "storePassword=$KEYSTORE_PASSWORD" >> android/key.properties
          echo "keyPassword=$KEY_PASSWORD" >> android/key.properties
          echo "keyAlias=$KEY_ALIAS" >> android/key.properties
          echo "storeFile=../release-key.jks" >> android/key.properties
        env:
          KEYSTORE_PASSWORD: ${{secrets.KEYSTORE_PASSWORD}}
          KEY_ALIAS: ${{secrets.KEY_ALIAS}}
          KEY_PASSWORD: ${{secrets.KEYSTORE_PASSWORD}}

      - name: Build release APK
        run: flutter build apk --release

      - name: Rename APK
        run: mv build/app/outputs/flutter-apk/app-release.apk wearcodes-release-${{ github.ref_name }}.apk&&mv build/app/outputs/flutter-apk/app-release.apk.sha1 wearcodes-release-${{ github.ref_name }}.apk.sha1
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: wearcodes-release-${{ github.ref_name }}.*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
